simple-microservices-private-key: |
      -----BEGIN OPENSSH PRIVATE KEY-----
      b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
      NhAAAAAwEAAQAAAYEA5YIO1ee8hlrGhrBg62GNy1/DvjHV6jnd2lOhjttb+99RkjZPhWwc
      xGLNZkenDaY7hiwcWOJtY7vHTUkxsZHnbnXzAQbNMuyVh0FfBNyQorKjzqZlt4UAJaRSoh
      lOUdenODltzKUQeDCZrZlrVSxmbK431Cyo0idcWAiVcrv0vDZUCNmhBRHScBoETxd/wJmk
      T9uVBYD/AYHehlROymj62LTlrDVAVc9mJjzP0hJSV7sAG5oZM+mIGDTpS+v1W3mKm+A72n
      aDEpqb21P5C1TEqeSIRw+dOfkXWEyCrBTZcj4GWO8CbzlLdfsL2pjrGT4HQnaQYZIbtb3e
      TwDsQqjU5cJFPIlzjtOUqeiK1YD27Rl3/LQ7ho+ZeBD1p4+GEAsy21MzpWUZ81H+ikeud6
      /hNE9R8aOkH6nCWBLyUADN2UtLS5/uqiTYZcNE8EazPLkKnPkxfhR5EeLzDUoCYSX0rA41
      NoOSNpZjcaGC9if5dehIwBsaXfk/EFXd9kgg5qd5AAAFeKrAMGeqwDBnAAAAB3NzaC1yc2
      EAAAGBAOWCDtXnvIZaxoawYOthjctfw74x1eo53dpToY7bW/vfUZI2T4VsHMRizWZHpw2m
      O4YsHFjibWO7x01JMbGR52518wEGzTLslYdBXwTckKKyo86mZbeFACWkUqIZTlHXpzg5bc
      ylEHgwma2Za1UsZmyuN9QsqNInXFgIlXK79Lw2VAjZoQUR0nAaBE8Xf8CZpE/blQWA/wGB
      3oZUTspo+ti05aw1QFXPZiY8z9ISUle7ABuaGTPpiBg06Uvr9Vt5ipvgO9p2gxKam9tT+Q
      tUxKnkiEcPnTn5F1hMgqwU2XI+BljvAm85S3X7C9qY6xk+B0J2kGGSG7W93k8A7EKo1OXC
      RTyJc47TlKnoitWA9u0Zd/y0O4aPmXgQ9aePhhALMttTM6VlGfNR/opHrnev4TRPUfGjpB
      +pwlgS8lAAzdlLS0uf7qok2GXDRPBGszy5Cpz5MX4UeRHi8w1KAmEl9KwONTaDkjaWY3Gh
      gvYn+XXoSMAbGl35PxBV3fZIIOaneQAAAAMBAAEAAAGBAJH0ahbiruQKqqJRXPGUMqaZml
      REQTQZ5NrJwL6nBhJh7PA9FclV/d1usA1RmA14H/at6sEkDkkUzCR8Xdv9W97Fp+qJNsoh
      5t4DVrgyxNCTJtVuwNU7AeLuY5au3T3zFWcOLqOsfZLR5YmfPcEG4YRQLzUBycMMQQ/DNb
      enjHZ9XmfabypYMSoVgZQC772+d95JWLYNWR7ORoPK7eiPZqeWM1GW8/keUmoS1l9UQ4WD
      aQgksc5vv5sVWyBrSLgJzEWsC6P8O4gFItbB8bnzj/T2Yob0Ug8msD+kOSi0hl+qUBe89+
      VlSPEeOO/G60Kcuc9cMHJu7+npQ9kSKLMBGFdUkLITLzS3k03gvhYcTGRllph/pcvPyTkE
      UNKx5inyl21t/tuU89abmitnmlN6S14AnL1OAECB8kneIlYBVAXdBl6ueR5/VXv84oWsv3
      7u7tIgnXSmPNrip+3mhA7W9Ojya9w2D7kh/mEgckfvl8LPca+fwh7HZRw0QYF4z5EdAQAA
      AMBStM+AKJlRgDHoyghXtUwRDpl0NUIIcjkOqCEziwOU4SaLUKOjihNdyjyOOfwUSX0C4X
      R/JdOBNUmL2RBtAx8nZXhV1NpFG4mhGZ1NRozeOHOsEG8ildTRs9ZQyklswum6QPoI5+TA
      odaubyAbg/gJnA0VHJXpJBs7wWtialg+PEQgHRZMLkHobyfKazt2l+IjK5fG2nVghFyNPB
      x1AxGvxkyjoqO2jNYoBL6i7f70Nu8SwwmM3pdp0VgN35qbG5wAAADBAOZGvn+Z3Bfze9NP
      26e4I2Ge23sfOxgeZC03MpeXXGAMvj9bFzbkk809eVQ9qVlLMIOJGHgtg9ccP6EPaugxyF
      PkE73z89FdBKBFcU9eKqGTeeQPlt5aa5HASym4rlZY9XYZ9cl4msWqMIbtslF37NIGeaf2
      5yyE42GA3qf/aeFjIxdfaZug8F1gisss16MwVfLJjT/L2aAcmuNSpkOW5I/pGORZYaKvov
      wGtzq+VyLK+LBSlJvnLoKtaw2uqKioyQAAAMEA/yVXqlgtbuLcMjJgN+IAhaTry+J4iu7D
      sGsEmO7bZ16/p2XN8Yb1qEdhnp6bdIuiAdq8SMZaOFOgQxqJlthr2/nI1mhhwPvpmJ4yxq
      cQWQY9AWYpXx3YKPydhmjUCnm79tAIt96YGCYDNjYdi22VkbDwxYlS+qxdp+8VKpsPIrAZ
      yKIcPO+q4kbAd9ST0otiojRch6yS6D0ep/FUDGQUmCzLvfNs1sS9EwC/9gYFB4gpYgt2ki
      nS6VFXEr8HoRExAAAAAAEC
      -----END OPENSSH PRIVATE KEY-----
image-repo-name: dfgdfg
registry-username: dfgdfg
registry-password: dfghdfg