resources:
# Repo with our docker files
- name: simple-microservices-code
  type: git
  source:
    uri: git@github.com:alexandercnigro/simple-microservices.git
    branch: main
    private_key: ((simple-microservices-private-key))

# Where we will push the image to
- name: simple-image
  type: registry-image
  icon: docker
  source:
    repository: ((image-repo-name))/simple-image
    username: ((registry-username))
    password: ((registry-password))

# jobs:
# - name: publish
#   public: true
#   serial: true
#   plan:
#   - get: tutorial
#   - put: hello-world-docker-image
#     params:
#       build: tutorial/tutorials/miscellaneous/docker-images/docker

jobs:
- name: build-cost-service
  plan:
  - get: simple-microservices-code # pull in simple-microservices code
  - task: build-image
    privileged: true # oci-build-task must run in a privileged container
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: concourse/oci-build-task
      inputs:
      - name: simple-microservices-code
      outputs:
      - name: image
      params:
        CONTEXT: simple-microservices-code/costService
      run: # binary used to build the image
        path: build
  - put: simple-image
    params:
      image: image/image.tar
# jobs:
#   - name: simple-microservices-job
#     plan:
#     - task: cost-svc-task
#       config:
#         platform: linux
#         image_resource:
#           type: docker-image
#           source:
#             repository: github
#         run:
#           path: echo
#           args: ["Hello world!"]