      
      simple-microservices-private-key: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAzblJaXtABwhLnHUFv8jIDLAyFCftmWZpGAuJJoQ+liDu0kgS/+FY
            x5pnhhJwKIxttG8RO03ydG5jYj1QmHOKdmgGDjRLhwsq/2mqyr+1KTVIHL12z4G4XSXrsZ
            I8HB6Cxj215SWOO+azXBp9m7Nszzc3GTX9PCSTVbJyTGaYXl7HhaZg5V3bN2mbfKbJsuub
            bL9o3GbUdwGuNmt+fhc2BodW0VMPl9J101t0+GXisibQfRahjh5bVZ1qyw4wceV9xPlTS3
            5nUWvN22c+q2GahWjt80f+C6qaZ+DwSSgtpjJbSivV2EppmT+sN5Ww2XMw+K64bBXa38Ez
            a3BxYJjdV+OK2gY/Gy7xfAPh48EhSR7rjtSb+0/w0NFbsTvxVvi8hhZq+UDHrfQCbYv3Al
            8HhboUj9uJuXmX1sW+mZF/v6VNcGP9xpWDiCJJcuIpxjitOCr59vIlQohi7jO7wjkqWS4B
            qUs7mvfgeea09O3dA2A/rvEIzfWPnOBh3Smvm47fAAAFeKrAMGeqwDBnAAAAB3NzaC1yc2
            EAAAGBAM25SWl7QAcIS5x1Bb/IyAywMhQn7ZlmaRgLiSaEPpYg7tJIEv/hWMeaZ4YScCiM
            bbRvETtN8nRuY2I9UJhzinZoBg40S4cLKv9pqsq/tSk1SBy9ds+BuF0l67GSPBwegsY9te
            Uljjvms1wafZuzbM83Nxk1/Twkk1WyckxmmF5ex4WmYOVd2zdpm3ymybLrm2y/aNxm1HcB
            rjZrfn4XNgaHVtFTD5fSddNbdPhl4rIm0H0WoY4eW1WdassOMHHlfcT5U0t+Z1FrzdtnPq
            thmoVo7fNH/guqmmfg8EkoLaYyW0or1dhKaZk/rDeVsNlzMPiuuGwV2t/BM2twcWCY3Vfj
            itoGPxsu8XwD4ePBIUke647Um/tP8NDRW7E78Vb4vIYWavlAx630Am2L9wJfB4W6FI/bib
            l5l9bFvpmRf7+lTXBj/caVg4giSXLiKcY4rTgq+fbyJUKIYu4zu8I5KlkuAalLO5r34Hnm
            tPTt3QNgP67xCM31j5zgYd0pr5uO3wAAAAMBAAEAAAGAVEIhWTyLutWg8lHTqvs3REseF7
            dKz1tsi9ads9LSN3cBmcq/TWIklIwe/oCqw1DQ1efvrNR+C0XzGpd2XRpliZ2NbV/p10Ox
            tq62rxfZwSj7ghnvgYnl0vDnGfGFARdWBI/d4h6BpPMWXxDShWT1meFJhd/g+jMYzS6rNb
            OHkI9NNOYyJX9Ne+KbNnCxh8CMBfxXnH3ZY2yix9M7GbW0APSJkG5uooYmkAyTWfGQ6dqP
            5cvRG34/dk9lIAmNufh9z+k4djHYAaffd6A++xzO/KiitRDWG1Cgne4dz+9biTLzdizOZm
            7Zsar8fb+vOqGFcn0vT1LA6K2ukmLzTBQq76YUjHE9Q8IAqmNBGYy1mIYthy1SajcPmegZ
            QuUpZx9X91B71cw6AuKrFZTjZqG4ZWTGka9jEpPwr8bC8fR4sKN4GWcLnmYg2FwSk0fhJi
            zywr08j/yfVHe7ikS+zry71OxgopLxKCwpTwAHXvZV0y2+l1E4YicQfaibwDGXkcARAAAA
            wHI/ogJTtqBJWLBBfvyhAzX2JHkDLl6NAtLEJgZc3MFNRz/Ls6djr5RsiC3Wamp3X0lECP
            jd4PdjHWwjaEMDFprmh84ipZLC2CLTxv4p+qAxajC5E8KgUiB7PlxPWA5X3I7sM6bsTg0/
            dkeK2h44AO/Ca1rWLjQ7rgQDZprJ1PmSQT6lJM8DiwNrQ/c7n4NqOkZxnvnwWWacsKUril
            MgIbaXHFqfrcC3adtMJQSpdpTqdjctGUJ1QS6jFJN7Ub9dZAAAAMEA+qeQFlQigQwBDBcj
            7fcV4Yc5mFbNlvb4/Z8NxPPRNKN8J+amXHl2kfORRNSVXYv5BLTBxUMBM5xoh5p1tBkwUJ
            j5nMYoXZaXJXCXR1dMw5VGectIazXkhF/eBE67j8k1z0G57V92aigxdVjq5J/H4Zr33y6J
            i8t4WAOg3m5DUbzga4liAsJHtSB1EWQ+x7p7M4oedideql0HYjobfOwUN3TyBEUtbQEPra
            Hzd8OO1lg5ggO/pBIfjq2osepr3LbjAAAAwQDSHG0q9RFf5H3AHPqRNAVmEIUD1Tb6Wazp
            Zsvufvxl0pSA28r8pzGgWGNFppp6xUi9EuB2i5XeIfBBpjRL5Bzr937icDKePlX8Ruv0ij
            BVvSow1s0+fJHtCP08oWei5g9DSrHwssIZdpJ/dSGjDHPlFBF4Sq7dIzqaU4is5P1R7In3
            Qw0XpCox1lSk/hNzZnBHzx6108QzHwQqhTQfbGHmNUxP0k8A4Ni9rs6VblFdsdjrouq2Vw
            EmIFJs8j5kTNUAAAAAAQID
            -----END OPENSSH PRIVATE KEY-----